name: Selenium Bookstore Test

on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, closed, synchronize]
      branches:
        - main

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # Specify the desired distribution here

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean package

      - name: Run Selenium tests
        run: mvn clean test


      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            test-output
            target/surefire-reports

